epam/badgerdoc

- lib/filter_lib/README.md
- lib/filter_lib/requirements.txt
- lib/filter_lib/src/query_modificator.py
- lib/filter_lib/src/schema_generator.py
- lib/filter_lib/tests/conftest.py
- lib/filter_lib/tests/test_query_modifier.py
* Add support of LTREE (Postgre-only) operations:
* "parent" - return parent of record with provided id
* "parents_recursive" - return all ancestors of record with provided id
* "children" - get first-level children for record with provided id
* "children_recursive" - get all descendants for record with provided id
* Add tests to cover this operations. Tests are checking sql statements for now because SQLite doesn't support LTREE data type
* Minor style fixes
> Feature: LTREE supported operations#2

- lib/filter_lib/src/query_modificator.py
Just run isort against `lib/filter_lib/src/query_modificator.py`
> hotfix: isort query_modificator

- lib/filter_lib/src/query_modificator.py
Fixed bug when filter_lib operators 'children_recursive' and 'children' returned corresponding siblings instead of direct children.
> fix: filter_lib children bug

- annotation/alembic/versions/6fb3e0d231ff_create_document_links_table.py
- annotation/alembic/versions/8ea2ff0fea64_create_association_doc_category_table.py
- annotation/app/annotations/main.py
- annotation/app/annotations/resources.py
- annotation/app/models.py
- annotation/app/schemas/__init__.py
- annotation/app/schemas/annotations.py
- annotation/tests/conftest.py
- annotation/tests/test_get_accumulated_revisions.py
- annotation/tests/test_get_annotation_for_particular_revision.py
- annotation/tests/test_get_revisions.py
- annotation/tests/test_get_revisions_without_annotation.py
- annotation/tests/test_post_annotation.py
> feat: documents pair classification

- web/src/components/task/task-sidebar-flow/index.tsx
- web/src/shared/components/document-pages/document-pages.tsx
Closes https://github.com/epam/badgerdoc/issues/456
Replaced the source of getting the names of annotators (from `users/users/search` to `jobs/jobs/{jobId}`)
> fix: replace the source of getting the names of annotators

- annotation/annotation/schemas/jobs.py
- annotation/tests/test_job_categories.py
- annotation/tests/test_post_job.py
- jobs/jobs/schemas.py
- jobs/tests/test_API_functions/test_args_validation.py
bug in issue_66 - cannot import label studio document with no annotations
> fix: fix validation on 'create_job' to allow import label studio doc with no annotations

- web/package.json
- web/src/components/task/task-sidebar-flow/annotation-list.tsx
- web/src/components/task/task-sidebar-flow/annotationRow.tsx
- web/src/connectors/task-annotator-connector/task-annotator-context.tsx
- web/src/shared/components/annotator/components/table-annotation/table-annotation.tsx
- web/src/shared/components/annotator/components/table-annotation/table-cell-layer/table-cell-layer.tsx
- web/src/shared/components/annotator/components/text-annotation/helpers.ts
- web/src/shared/components/annotator/components/text-annotation/text-annotation.tsx
- web/src/shared/components/annotator/components/text-label/text-label.tsx
- web/src/shared/components/document-pages/components/document-pdf/index.tsx
- web/src/shared/components/document-pages/document-pages.module.scss
- web/src/shared/components/document-pages/document-pages.tsx
- web/src/shared/components/document-pages/types.ts
- web/yarn.lock
**Actual result**: when PDF doc with 1000 pages is opened, the browser's tab with the app is crashed.
**Expected result**: PDF doc with 1000 pages is opened without crashing. 
In the scope of this PR, performance for rendering process of PDF docs was improved.
PR is not tested on potential example with a lot of annotations, only with big PDF file (about 1000 pages and couple of shown annotations).
The main approach is to use `react-window` library to render only part of PDF file, during scrolling this part will be updated. This will allow us to not keep a lot of DOM elements at the same time (otherwise the browser may not have enough RAM for such big count of elements).
Also, `Page`'s `renderTextLayer` is set to `false` to not render selectable text above PDF - as we discussed with …
> perf: improve performance for rendering process of long PDF documents

- web/src/components/task/task-sidebar/finish-button/finish-button.tsx
In the scope of this PR, the conditions to show a tooltip for the FinishButton are fixed
> fix: Fixes Finish Validation/Labelling Button Tooltip

- web/src/components/task/task-sidebar/finish-button/utils.ts
This PR addresses the issue of a very long list of remaining pages appearing on the tooltip of the finish validation button.
It consists on the creation of a set of utils that will handle the cases when more than 10 pages are remaining
> fix: Tooltip With Very Long List Of Pages

- web/package.json
- web/src/api/hooks/annotations.ts
- web/src/components/task/task-sidebar-flow/__tests__/annotation-list.test.tsx
- web/src/components/task/task-sidebar-flow/annotation-list.tsx
- web/src/components/task/task-sidebar-flow/task-sidebar-flow.module.scss
- web/src/components/task/task-sidebar-flow/task-sidebar-flow.tsx
- web/src/components/task/task-sidebar/task-sidebar.tsx
- web/src/connectors/task-annotator-connector/task-annotator-context.tsx
- web/src/connectors/task-annotator-connector/task-annotator-utils.ts
- web/src/connectors/task-annotator-connector/use-document-data-full-loading/index.ts
- web/src/connectors/task-annotator-connector/use-document-data-full-loading/types.ts
- web/src/connectors/task-annotator-connector/use-document-data-full-loading/use-tokens-full-loading.ts
- web/src/connectors/task-annotator-connector/use-document-data-lazy-loading/index.ts
- web/src/connectors/task-annotator-connector/use-document-data-lazy-loading/types.ts
- web/src/connectors/task-annotator-connector/use-document-data-lazy-loading/use-annotations-lazy-loading.ts
- web/src/connectors/task-annotator-connector/use-document-data-lazy-loading/use-cached-data-pages-range.ts
- web/src/connectors/task-annotator-connector/use-document-data-lazy-loading/use-tokens-lazy-loading.ts
- web/src/connectors/task-annotator-connector/use-document-links.ts
- web/src/connectors/task-annotator-connector/use-validation.tsx
- web/src/shared/components/annotator/utils/use-annotation-links.ts
- web/src/shared/components/document-pages/components/document-pdf/index.tsx
- web/src/shared/helpers/scroll-into-view-if-needed.ts
- web/yarn.lock
The goal of this PR is to improve performance of loading big PDF files (1000+) pages where we may potentially have up to 50 annotations. Unfortunately, this PR is quite big because during development there were a lot of different experiments which touched different parts of the app. It might be possible to split it into smaller PRs and merge them separately but this may require also a lot of time to re-test a lot of stuff for split functionality (it's easy to break something). Cos of this I propose to keep this solid PR.
In the future, it would be a good step to have refactoring mostly for the existing big react context because it contains tons of logic for different document modes  like "Validation only" / "Cross validation" etc. This modes may have own context/own hooks/own components.
> perf: load annotations for PDF in chunks

- web/src/shared/components/annotator/components/box-annotation/box-annotation.module.scss
This PR addresses the issue of wrapping text for the box annotation labels
> fix: Introduces no-wrap for box annotation label

- web/src/components/task/task-sidebar/finish-button/finish-button.tsx
- web/src/components/task/task-sidebar/finish-button/utils.ts
- web/src/components/task/task-sidebar/task-sidebar.tsx
- web/src/components/task/task-sidebar/utils.ts
This PR addresses the issues raised about the Tooltips of the Finish and Save Button
> fix: Tootips for uncovered Task Status cases

- web/src/components/task/task-sidebar/finish-button/confirm-modal/confirm-modal.tsx
- web/src/components/task/task-sidebar/finish-button/finish-button.tsx
Confirm modal only when annotation finished. 
New text added to confirm modal.
> fix: show "confirm" modal only when annotation is finished

- web/src/connectors/categories-modal-connector/categories-modal-connector.tsx
- web/src/connectors/categories-modal-connector/styles.module.scss
- web/src/connectors/categories-modal-connector/utils.ts
This PR addresses the issues described of the edit categories modal
For the given context of editing an existing category:
- Adds a new class to hide category-id field
- Fixes utils the map existing category values to the form values
- Implements necessary changes on Modal component
> fix: Edit Categories Modal

- web/src/components/task/task-sidebar/utils.ts
The goal of this PR is to introduce a specific tooltip for the SaveDraft button for In Progress validation tasks
> fix: implements tooltip for in progress validation tasks

- web/src/components/task/task-sidebar/task-sidebar.tsx
- web/src/components/task/task-sidebar/utils.ts
Second PR of SaveDraft button tooltip. Now, the isValidation argument is passed by the caller to the tooltip calculation function
> fix: save button tooltip

- web/src/shared/components/annotator/components/text-annotation/helpers.ts
This PR fixes the behavior of creating a text annotation.
The previous code was not identifying line breaks correctly, so a new condition for line break was added.
> fix: introduces prevToken evaluation into new line calculation

- web/src/components/task/task-document-pages/task-document-pages.tsx
- web/src/connectors/task-annotator-connector/task-annotator-context.tsx
- web/src/pages/document/document-page.module.scss
- web/src/pages/document/document-page.tsx
- web/src/pages/task/task-page.module.scss
- web/src/pages/task/task-page.tsx
- web/src/shared/components/document-pages/components/document-pdf/index.tsx
- web/src/shared/components/document-pages/components/document-pdf/types.ts
- web/src/shared/components/document-pages/document-pages.tsx
- web/src/shared/components/document-pages/document-single-page.tsx
- web/src/shared/components/document-pages/types.ts
- web/src/shared/components/document-toolbar/index.tsx
- web/src/shared/components/document-toolbar/styles.module.scss
In the scope of this PR, currently shown page's order number is in the dropdown when page is scrolled. "Go to page" is renamed to "Current page".
> feat: reflect currently shown page's order number in "Current page" dropdown when page is scrolled

- web/src/connectors/job-detail-view-connector/job-detail-view-connector.tsx
- web/src/connectors/tasks/create-task/create-task.tsx
This PR aims to add logic to close the CreateTask Modal on successful task creation.
The approach consists on passing down a handleCloseModal function as a prop to the CreateTask component
> fix: Close Create Task Modal On Save

- web/src/components/categories/categories-tab/categories-tab.tsx
- web/src/components/categories/categories-tree/use-categories-tree.tsx
- web/src/connectors/task-annotator-connector/task-annotator-context.tsx
In the scope of this PR, the issue with showing UI spinners/skeleton loaders not in time is fixed.
> fix: show skeleton-loader and spinner when they are needed

- web/src/shared/components/annotator/components/text-annotation/text-annotation.tsx
In the scope of this PR, we remove "jump" effect when annotation is removed.
> fix: remove doc jumping when annotation is removed

- web/src/components/task/task-sidebar-flow/__tests__/annotation.test.tsx
- web/src/components/task/task-sidebar-flow/annotation-list.tsx
- web/src/components/task/task-sidebar-flow/annotationRow.tsx
- web/src/components/task/task-sidebar-flow/types.ts
If the task is in the finished status, and also during validation outside of page editing, the delete of annotations function becomes impossible.
> fix: blocking deletion of annotations in some scenarios.

- web/src/connectors/documents-page-control-connector/documents-page-control-connector.tsx
- web/src/connectors/documents-page-control-connector/fetch-with-tracking-of-upload-progress-factory.ts
- web/src/connectors/documents-page-control-connector/use-fetch-with-tracking-of-upload-progress.ts
- web/src/connectors/documents-page-control-connector/use-notify-processing.ts
The goal of this PR is to show notifications when file processing takes more than 10 seconds.
After first notification, next one will be in 20sec and on every time notification is shown, delay is doubled.
For that was implemented `useNotifyProcessing` hook, which will watch `isUploadedValue` from `useFetchWithTrackingOfUploadProgress` and trigger the notifications based on that.
> feat: Post upload processing notifications

- annotation/tests/test_distribution.py
This pr contains tests for testing the function _create_tasks_ in the file /tests/test_distribution.py. 
The test covers two cases of the functions use. First case is when the amount of pages to assign is less than the MAX_PAGES attribute and the second case covers when the files have to be split to multiple tasks.
> test(annotation): cover create_tasks

- annotation/annotation/annotations/main.py
- annotation/annotation/annotations/resources.py
- annotation/annotation/filters.py
- annotation/annotation/jobs/resources.py
- annotation/annotation/schemas/jobs.py
- jobs/alembic/versions/a4b7b64a472c_add_revisions_field_to_job.py
- jobs/jobs/airflow_utils.py
- jobs/jobs/create_job_funcs.py
- jobs/jobs/databricks_utils.py
- jobs/jobs/db_service.py
- jobs/jobs/models.py
- jobs/jobs/pipeline.py
- jobs/jobs/run_job_funcs.py
- jobs/jobs/schemas.py
- jobs/jobs/utils.py
- jobs/tests/test_utils.py
> feat: revision based jobs

- web/src/connectors/documents-table-connector/documents-table-connector.tsx
- web/src/connectors/edit-job-connector/edit-job-connector.tsx
- web/src/pages/document/document-page-sidebar-content/document-page-sidebar-content.tsx
- web/src/pages/jobs/edit-job-page.tsx
Go to BadgerDoc platform -> "Documents" tab
Select a check box for some files (or one file)
Press "+Add to extraction"
Expected result:
The file selected on "Documents" tab is selected on the "Datasets" page
Key changes:
- Updated useEffect to initialize selected files using `fileIds` from the location state.
- Added `fileIds` prop to `DocumentsTableConnector` for transferring file selection from previous actions.
- Ensured file selections persist when navigating between "Documents" and other pages.
> fix: persist file selection when adding to extraction (#785) 

- jobs/jobs/config.py
- jobs/jobs/main.py
- jobs/jobs/utils.py
- jobs/pytest.ini
- jobs/tests/test_utils.py
- processing/processing/config.py
> fix: files are not shown when a job is created using revisions

- web/src/shared/components/document-toolbar/index.tsx
- Added controlled input state management for PickerInput component
- Implemented useEffect to sync input value with current page changes
- Added direct keyboard event handling via rawProps.input
- Included input validation for page number boundaries
- Maintained existing dropdown selection functionality
Fixes issue where enter key press didn't navigate to selected page
https://github.com/user-attachments/assets/da37bbc8-4385-499e-9a84-038788efea22
> feat: enable enter key navigation in page picker

- web/src/App.tsx
- web/src/shared/constants/general.ts
Steps to reproduce:
Login as a non-admin user
Try to open http://badgerdoc-dev.westeurope.cloudapp.azure.com:8083/categories (f.e.) or any other page/tab that is shown only for admin users
Expected result:
Non-admin user should not have access to these pages
Expected result is met.
A non-admin user no longer has access to modify or annotate items they shouldn’t have access to. The only change they can make is creating a new Category. If it is not a requirement, it’s up to the backend to decide whether this endpoint should be restricted for non-admins. 
This pr blocks the Category route on the frontend side — all other routes are working fine.
> fix: Non-admin user can access files and tabs via direct link #777
