lib/filter_lib/src/query_modificator.py
web/src/components/task/task-document-pages/task-document-pages.tsx
web/src/connectors/task-annotator-connector/task-annotator-context.tsx
web/src/connectors/task-annotator-connector/task-annotator-utils.ts
web/src/shared/components/annotator/annotator.tsx
web/src/shared/components/annotator/components/link-annotation/helpers.ts
web/src/shared/components/annotator/components/link-annotation/link-annotation.module.scss
web/src/shared/components/annotator/components/link-annotation/link-annotation.tsx
web/src/shared/components/annotator/components/text-annotation/helpers.ts
web/src/shared/components/annotator/components/text-annotation/text-annotation.module.scss
web/src/shared/components/annotator/components/text-annotation/text-annotation.tsx
web/src/shared/components/annotator/components/text-label/text-label.tsx
web/src/shared/components/annotator/layers/annotations-layer/annotations-editable-renderer.tsx
web/src/shared/components/annotator/typings.ts
web/src/shared/components/annotator/utils/get-points-for-link.ts
web/src/shared/components/document-pages/document-single-page.tsx

Resolved merge conflict with main

fix: merge conflict

---

web/src/components/dataset/dataset-choose-form.tsx
web/src/components/dataset/dataset-row/dataset-row.tsx
web/src/connectors/documents-card-connector/documents-card-connector.tsx
web/src/connectors/documents-sidebar-connector/documents-sidebar-connector.tsx
web/src/connectors/documents-table-connector/documents-table-connector.tsx
web/src/connectors/tasks/create-task/create-task.tsx
web/src/shared/helpers/set-filters.ts
web/src/shared/hooks/page-table-hook.ts

Fixed bug with getting datasets when filtering

fix: bug with datasets filters

---

web/src/connectors/SH-dashboard-table-connector/sh-columns.tsx
web/src/connectors/job-detail-view-connector/job-tasks-column.tsx
web/src/connectors/tasks-table-connector/tasks-columns.tsx

Fixed display of deadline if it is not set (null)
[issue #68](https://github.com/epam/badgerdoc/issues/68)

fix: date display on front if value is null

---

annotation/alembic/versions/e56cb55fde06_document_category_enum_type.py
annotation/app/schemas/categories.py

feat: add document categorytypeschema enum

---

taxonomy/app/taxon/services.py
taxonomy/app/taxonomy/resources.py
taxonomy/app/taxonomy/services.py
taxonomy/docker-compose.yml
taxonomy/tests/test_taxonomy_router.py

feat: add current tenant header to all taxonomy resources

---

annotation/app/annotations/main.py
annotation/app/annotations/resources.py
annotation/app/models.py
annotation/app/schemas/annotations.py
annotation/tests/test_get_accumulated_revisions.py
annotation/tests/test_get_annotation_for_particular_revision.py
annotation/tests/test_get_revisions.py
annotation/tests/test_get_revisions_without_annotation.py
annotation/tests/test_post_annotation.py

fix: save document categories for each revision

---

annotation/.env
annotation/app/microservice_communication/search.py
annotation/app/microservice_communication/user.py
annotation/app/schemas/tasks.py
annotation/app/tasks/resources.py
annotation/tests/test_microservices_search.py
annotation/tests/test_post_next_task.py
annotation/tests/test_tasks_crud_cr.py

Feat/add username in response#127

---

taxonomy/app/taxonomy/services.py

fix: add check for taxonomy in get_taxonomy function

---

annotation/app/main.py

fix: add app exceptions middleware with logger

---

lib/filter_lib/src/query_modificator.py

fix: taxon search bug on null value with the in operator

---

web/src/api/hooks/documents.ts
web/src/connectors/documents-table-connector/documents-table-connector.tsx
web/src/pages/documents/documents-page.tsx

feat: Add possibility to delete documents on documents page

---

web/src/connectors/categories-modal-connector/categories-modal-connector.tsx

fix: extract error message on category create/update step

---

assets/.env
assets/chart/templates/deployment.yaml
assets/src/utils/common_utils.py

https://github.com/epam/badgerdoc/issues/147
https://github.com/epam/badgerdoc/pull/207
[x] Fixed deployment.yaml
[x] Removed txt processing from gutenberg
[x] Fixed name of path for storing tokens

Fix according to code-review

---

web/package.json
web/src/components/task/task-document-pages/task-document-pages.tsx
web/yarn.lock

closes https://github.com/epam/badgerdoc/issues/183

fix: forbid annotation if task is not in Ready or In Progress status

---

web/src/components/taxonomies/taxonomies-tree.module.scss
web/src/shared/components/badger-tree/badger-tree.module.scss
web/src/shared/components/badger-tree/badger-tree.tsx
web/src/shared/components/badger-tree/rc-tree.scss

Fix/taxonomy tree#222

---

web/src/components/labels-panel/labels-panel.tsx
web/src/components/task/task-sidebar/task-sidebar.tsx
web/src/shared/no-data/no-data.module.scss
web/src/shared/no-data/no-data.tsx

closes https://github.com/epam/badgerdoc/issues/267

fix: label's btn functionality

---

web/src/api/mocks/index.ts
web/src/api/mocks/tasks.ts
web/src/connectors/job-detail-view-connector/job-detail-view-connector.tsx

Closes https://github.com/epam/badgerdoc/issues/256

Fix/pagination task list#256

---

README.md

Base image build and local dependencies installation instructions have been added

README: local setup

---

assets/src/routers/files_router.py

Files number limitation has been disabled for "Upload Wizard"
Closes https://github.com/epam/badgerdoc/issues/254

Feat: disable uploading files number limitation

---

web/src/api/hooks/bonds.ts
web/src/api/typings/bonds.ts
web/src/pages/upload-document-wizard/upload-document-wizard-page.tsx
web/src/shared/components/wizard/dataset-wizard-screen/dataset-wizard-screen.tsx

closes https://github.com/epam/badgerdoc/issues/255

fix: add file bonding to datasets in upload wizard

---

web/src/api/mocks/tasks.ts
web/src/connectors/job-detail-view-connector/job-detail-view-connector.tsx

Closes https://github.com/epam/badgerdoc/issues/258

fix: sorting of tasks of an annotation jobs

---

convert/poetry.lock
convert/pyproject.toml
convert/src/label_studio_to_badgerdoc/badgerdoc_format/pdf_renderer.py

fix: add cjk fonts to pdf generation

---

web/src/components/labels-panel/labels-panel.tsx
web/src/components/pipeline/pipeline-form-field/pipeline-form-field.tsx
web/src/components/task/task-sidebar-labels/task-sidebar-labels.module.scss
web/src/components/task/task-sidebar-labels/task-sidebar-labels.tsx
web/src/components/task/task-sidebar/task-sidebar-labels-links/task-sidebar-labels-links.tsx
web/src/components/task/task-sidebar/task-sidebar.tsx
web/src/connectors/task-annotator-connector/task-annotator-context.tsx
web/src/shared/components/document-pages/document-pages.tsx

Closes https://github.com/epam/badgerdoc/issues/285

feat: remove the ability to edit labels on the "documents" tab

---

annotation/app/annotations/main.py
annotation/app/annotations/resources.py
annotation/app/schemas/annotations.py
annotation/app/tasks/resources.py
annotation/tests/test_get_pages_info.py

Fix validation for empty save, extract categories for doc summary from revisions history

---

taxonomy/app/schemas/__init__.py
taxonomy/app/schemas/taxon.py
taxonomy/app/taxon/resources.py
taxonomy/app/taxon/services.py
taxonomy/tests/test_taxon_crud.py

feat: add parents_concatenate taxon name and id endpoint

---

web/src/components/task/task-sidebar-labels/task-sidebar-labels.module.scss
web/src/components/task/task-sidebar/task-sidebar-labels-links/task-sidebar-labels-links.module.scss
web/src/shared/components/badger-tree/badger-tree.tsx

Also fixed label list scrolling

fix: category list scroll bar

---

convert/docker-compose.yaml
convert/src/label_studio_to_badgerdoc/badgerdoc_format/plain_text_converter.py
convert/tests/test_label_studio/test_text_wrapper.py

1) Fix text line wrapping
2) Fix white spaces at the beginning of a line

Feat: Improve text line wrapper

---

web/src/shared/hooks/page-table-hook.ts

fix: pagination on job files tab

---

convert/src/label_studio_to_badgerdoc/badgerdoc_format/annotation_converter_practic.py
convert/src/label_studio_to_badgerdoc/badgerdoc_to_label_studio_use_case.py
convert/src/label_studio_to_badgerdoc/labelstudio_format/label_studio_format.py
convert/src/label_studio_to_badgerdoc/models/bd_manifest_model_practic.py
convert/src/routers/label_studio.py

add taxonomies and document_labels support to_export to label studio

---

web/src/components/taxonomies/map-taxonomies.ts
web/src/components/taxonomies/taxonomies-tree.tsx
web/src/components/taxonomies/use-taxonomies-tree.tsx
web/src/shared/helpers/get-taxon-full-name.ts
web/src/shared/hooks/use-annotations-taxons.ts

Closes [#250](https://github.com/epam/badgerdoc/issues/250)

feat: add full path for taxon

---

web/src/components/task/task-sidebar/task-sidebar.tsx

fix: Remove unnecessary request

---

annotation/app/annotations/main.py
annotation/app/schemas/annotations.py
annotation/tests/fixtures/expected_all_revisions.json
annotation/tests/fixtures/expected_latest_revisions.json

Issue: #247 
Added categories (document-level labels) on
get_latest_revision_by_user and get_all_revisions endpoints.

feat: add categories on PageOutSchema

---

web/.gitignore
web/README.md
web/config/jest/__mocks__/svg.ts
web/config/jest/decorators/withRouter.tsx
web/config/jest/jest.config.ts
web/package.json
web/src/shared/components/breadcrumb/breadcrumb-navigation.test.tsx
web/yarn.lock

- add configuration for jest
- add commands for run tests
- create one test for example case

Feat: implement test

---

web/src/components/task/task-sidebar/task-sidebar.module.scss

empty space removed
Closes #329

fix: styling on validation view

---

web/src/api/hooks/api.ts
web/src/api/hooks/jobs.ts
web/src/connectors/edit-job-connector/edit-job-connector.tsx

Fixes the frontend part of this issue: https://github.com/epam/badgerdoc/issues/292

fix: edit job#292

---

web/src/connectors/task-annotator-connector/use-split-validation.ts
web/src/shared/components/annotator/annotator.tsx
web/src/shared/components/annotator/components/link-annotation/helpers.ts

Closes [#291](https://github.com/epam/badgerdoc/issues/291)

fix: transferring relation from annotation of different users

---

web/src/pages/jobs/edit-job-page.tsx

Closes [#373](https://github.com/epam/badgerdoc/issues/373)

fix: redirect to extraction page after finish editing

---

annotation/app/jobs/resources.py
annotation/app/jobs/services.py
annotation/app/schemas/jobs.py
jobs/jobs/schemas.py

Save extensive_cov param, add some validations

---

annotation/app/tasks/resources.py
annotation/app/tasks/services.py
annotation/tests/conftest.py
annotation/tests/test_finish_task.py

feat: transfer matching annotations

---

web/src/api/typings/jobs.ts
web/src/connectors/task-annotator-connector/use-split-validation.ts
web/src/connectors/task-annotator-connector/use-validation.tsx
web/src/shared/components/job/job-detail-view-header.tsx
web/src/shared/components/job/job-sidebar-header.tsx
web/src/shared/components/status/status.tsx

closes https://github.com/epam/badgerdoc/issues/415

fix: attempt to finish completed task extensive coverage#415

---

web/src/api/typings/jobs.ts
web/src/connectors/edit-job-connector/edit-job-connector.tsx
web/src/connectors/job-detail-view-connector/job-detail-view-connector.tsx
web/src/connectors/job-detail-view-sidebar-connector/job-detail-view-sidebar-connector.tsx
web/src/connectors/task-annotator-connector/user-fetch-hook.ts

prepare code to receive array of objects in annotators field, not array of strings

feature: The author of the labelling in the validation task

---

web/src/components/task/task-sidebar/task-sidebar.tsx

fix: Error is displayed when clicking on the annotation (the document is imported from MinIO)

---

web/src/connectors/task-annotator-connector/task-annotator-context.tsx
web/src/pages/task/task-page.tsx
web/src/shared/components/notifications/index.tsx

Closes https://github.com/epam/badgerdoc/issues/430

fix: annotation task finished status in extensive coverage#430

---

web/src/components/job/automatic-manual-job/automatic-manual-job.tsx
web/src/components/job/edit-job-settings/edit-job-settings.tsx
web/src/shared/components/wizard/wizard/wizard.tsx

Closes https://github.com/epam/badgerdoc/issues/450

fix: wrong state for job page#450

---

web/src/connectors/edit-job-connector/edit-job-connector.tsx
web/src/pages/jobs/edit-job-page.tsx

Closes https://github.com/epam/badgerdoc/issues/458
+Added validationMessage to input annotators_validators for hierarchical validation.

fix: condition to create job form

---

web/src/components/task/task-sidebar-flow/task-sidebar-flow.tsx
web/src/connectors/task-annotator-connector/use-split-validation.ts
web/src/pages/document/document-page.tsx
web/src/pages/task/task-page.tsx

Fixes for https://github.com/epam/badgerdoc/issues/456

fix: render title of annotators for cross and hierarchical validation

---

annotation/annotation/distribution/__init__.py
annotation/annotation/distribution/main.py
annotation/annotation/jobs/__init__.py
annotation/annotation/jobs/resources.py
annotation/annotation/jobs/services.py
annotation/tests/conftest.py
annotation/tests/test_update_job.py

fix: change job editing behavior

---

jobs/Dockerfile
jobs/jobs/schemas.py
jobs/tests/test_API_functions/test_args_validation.py

Fix validation for an extraction job.
Optimize Dockerfile for faster build.
Closes #489

fix: fix validation for an extraction job

---

annotation/annotation/jobs/resources.py
annotation/annotation/jobs/services.py

fix: change deleting job tasksfix: change deleting job tasks

---

annotation/annotation/tasks/services.py

fix: change tasks indexing

---

web/src/connectors/task-annotator-connector/task-annotator-utils.ts

fixes for https://github.com/epam/badgerdoc/issues/66

feat: add bbox from annotation text type

---

web/src/components/task/task-sidebar/finish-button/finish-button.tsx
web/src/components/task/task-sidebar/finish-button/utils.ts
web/src/components/task/task-sidebar/task-sidebar.tsx

Closes https://github.com/epam/badgerdoc/issues/504

fix: logic for finish button

---

web/src/components/task/task-sidebar-flow/task-sidebar-flow.tsx
web/src/connectors/task-annotator-connector/use-split-validation.ts

fix: Send request for annotations by user only if the task has splitValidation type

---

web/src/components/task/task-modal/constants.ts
web/src/components/task/task-modal/task-validation-modal.tsx
web/src/connectors/task-annotator-connector/use-validation.tsx
web/src/shared/components/notifications/index.tsx
web/src/shared/helpers/get-error.tsx

fix: Fixed closing of finished modal window

---

web/src/components/file-upload/upload-form/upload-form.tsx
web/src/components/upload-files-control/upload-files-control.tsx
web/src/connectors/documents-page-control-connector/documents-page-control-connector.tsx
web/src/pages/upload-document-wizard/upload-document-wizard-page.tsx
web/src/shared/components/wizard/dataset-wizard-screen/constants.ts
web/src/shared/components/wizard/dataset-wizard-screen/dataset-wizard-screen.tsx

fix: Fixed uploading files with the same name

---

.env.example
README.md
docker-compose-dev.yaml

Specify .env for local docker-compose.
Correct the instruction.

fix: correct files for local development

---

convert/convert/converters/labelstudio/labelstudio_format.py
convert/tests/labelstudio/export/test_export_with_links/data/badgerdoc/annotation/manifest.json

fix: fix work with manifest files

---

.github/workflows/pr-lint.yml
CONTRIBUTING.md

feat(actions): add pull request title linter

---

web/src/shared/components/annotator/components/box-annotation/box-annotation.module.scss
web/src/shared/components/annotator/components/box-annotation/box-annotation.tsx

fix: Render annotation's label only on hover/selection

---

web/src/pages/task/picker-grid-type/picker-grid-type.tsx
web/src/pages/task/task-page.module.scss
web/src/pages/task/task-page.tsx

fix: Made select non editable && made next button fixed width

---

web/src/components/task/task-sidebar/task-sidebar.tsx
web/src/connectors/task-annotator-connector/task-annotator-context.tsx
web/src/shared/components/annotator/typings.ts
web/src/shared/components/annotator/utils/use-annotation-links.ts

fix: Create a link only once

---

web/src/components/task/task-sidebar/task-sidebar.module.scss
web/src/components/task/task-sidebar/task-sidebar.tsx
web/src/connectors/tasks-table-connector/constants.tsx
web/src/connectors/tasks-table-connector/tasks-table.module.scss
web/src/shared/helpers/copy-text.tsx

feat: added copy icon

---

web/src/components/taxonomies/use-taxonomies-tree.tsx

fix: Hide loader if there are no taxons

---

web/src/shared/components/annotator/utils/use-annotation-links.ts

fix: Clear saved annotation after link creation

---

web/src/components/task/task-sidebar-flow/annotation.tsx
web/src/components/task/task-sidebar-flow/links/index.tsx
web/src/components/task/task-sidebar-flow/utils.ts
web/src/connectors/task-annotator-connector/task-annotator-utils.ts
web/src/shared/components/annotator/annotator.tsx
web/src/shared/components/annotator/links-layer.tsx
web/src/shared/components/annotator/typings.ts
web/src/shared/components/annotator/utils/get-points-for-link.ts
web/src/shared/components/annotator/utils/use-annotation-links.ts
web/src/shared/components/document-pages/document-single-page.tsx
web/src/shared/components/observed-element/observed-element.tsx
web/src/shared/hooks/use-annotations-mapper.ts

feat: Added possibility to create links between annotaitons at deferent pages

---

annotation/annotation/tasks/resources.py
annotation/tests/test_tasks_crud_cr.py

fix: work of next button#554

---

web/src/connectors/tasks-table-connector/tasks-table-connector.tsx
web/src/connectors/tasks-table-connector/use-job-filter.ts

feat: added job filter on dashboard

---

web/src/api/typings.ts
web/src/components/taxonomies/use-taxonomies-tree.tsx

Closes https://github.com/epam/badgerdoc/issues/548

feat: delete 'parent_id' field on taxons text search

---

web/src/connectors/task-annotator-connector/task-annotator-context.tsx
web/src/shared/components/annotator/components/link-annotation/link-annotation.module.scss

fix: links creation & deletion

---

annotation/.env
annotation/annotation/schemas/annotations.py
annotation/tests/test_post_annotation.py

fix: fix validation schema for extensive coverage

---

web/src/api/hooks/tasks.ts
web/src/components/task/task-sidebar/finish-button/finish-button.tsx
web/src/connectors/task-annotator-connector/task-annotator-context.tsx
web/src/connectors/task-annotator-connector/use-split-validation.ts
web/src/shared/components/document-pages/document-pages.tsx

feat: extensive coverage one response instead of two on finish#569

---

web/src/components/task/task-sidebar-flow/annotation-list.tsx
web/src/components/task/task-sidebar-flow/task-sidebar-flow.tsx
web/src/connectors/task-annotator-connector/task-annotator-context.tsx
web/src/connectors/task-annotator-connector/utils.ts

Closes https://github.com/epam/badgerdoc/issues/608

fix: render annotation duplicates in left sidebar

---

annotation/Dockerfile
annotation/annotation/distribution/main.py
annotation/tests/test_distribution.py

fix: recursion error for large annotation files

---

web/src/api/typings.ts
web/src/components/job/automatic-manual-job/automatic-manual-job.tsx
web/src/components/job/edit-job-settings/edit-job-settings.tsx
web/src/connectors/edit-job-connector/edit-job-connector.tsx
web/src/shared/components/categories-picker/categories-picker.tsx

Closes https://github.com/epam/badgerdoc/issues/432

feat: add lazy loading for categories picker data scroll

---

annotation/annotation/tasks/services.py
annotation/tests/test_finish_task.py

fix: change common objs search

---

web/src/connectors/document-page-connector/document-page-connector.tsx
web/src/pages/document/document-page-sidebar-content/document-page-sidebar-content.tsx

Closes https://github.com/epam/badgerdoc/issues/598

fix: show correct revision when changing jobId

---

web/src/connectors/edit-job-connector/edit-job-connector.tsx

fix: Edit job bug fix #636

---

web/src/components/task/task-document-pages/task-document-pages.tsx
web/src/pages/document/document-page.module.scss
web/src/pages/document/document-page.tsx
web/src/shared/components/document-pages/document-pages.tsx
web/src/shared/components/document-pages/document-single-page.tsx
web/src/shared/components/observed-element/observed-element.tsx

feat: Implemented navigation through pdf pages

---

convert/chart/templates/deployment.yaml

fix: correct env variable for keycloak url

---

annotation/annotation/filters.py
annotation/annotation/jobs/__init__.py
annotation/annotation/jobs/services.py
annotation/annotation/microservice_communication/assets_communication.py
annotation/annotation/microservice_communication/jobs_communication.py
annotation/annotation/microservice_communication/search.py
annotation/annotation/tasks/resources.py
annotation/annotation/tasks/services.py
annotation/documentation/openapi.yaml
annotation/tests/test_microservices_search.py
annotation/tests/test_tasks_crud_cr.py
lib/filter_lib/setup.py
lib/filter_lib/src/enum_generator.py
lib/filter_lib/src/schema_generator.py

feat: add params in tasks search

---

web/src/connectors/tasks-table-connector/tasks-table-connector.tsx
web/src/connectors/tasks-table-connector/use-job-filter.ts
web/src/connectors/tasks-table-connector/use-name-filter.ts

feat: Implemented filtering by file name and job name

---

web/src/connectors/edit-job-connector/edit-job-connector.tsx

Closes #637 
The current bug was related to disappearance of categories with only type 'Link' so we decided to restrict of selection Link type only in stage of creating job.

fix: Fix bug related to disappearing categories with only type Link

---

web/src/shared/components/document-pages/document-pages.module.scss
web/src/shared/components/document-pages/document-pages.tsx

fix: Fix vertical view for annotators sections

---

lib/filter_lib/setup.py
lib/filter_lib/src/pagination.py
lib/filter_lib/src/query_modificator.py
lib/filter_lib/tests/test_pagination.py

fix: fix pagination

---

assets/assets/routers/files_router.py
assets/assets/routers/s3_router.py

Relates to https://github.com/epam/badgerdoc/issues/615

fix: fix synchronous calls from async routes

---

models/models/colab_ssh_utils.py
models/models/utils.py
models/tests/conftest.py
models/tests/test_utils.py

fix: fix storage host for deploying services via the models service

---

web/src/connectors/task-annotator-connector/task-annotator-context.tsx

fix: ISSUE-657   Fixed deleting one link, deletes all links

---

web/src/components/task/task-sidebar-flow/annotation-list.tsx
web/src/components/task/task-sidebar-flow/label-row.tsx
web/src/components/task/task-sidebar-flow/task-sidebar-flow.tsx
web/src/pages/task/task-page.module.scss
web/src/pages/task/task-page.tsx
web/src/shared/components/labels/index.ts
web/src/shared/components/labels/labels.tsx
web/src/shared/hooks/use-labels.ts

This pull request is related only to the first point of issue #676

feat: Move labels from left sidebar to top of document

---

models/models/constants.py
pipelines/pipelines/config.py
pipelines/pipelines/s3.py
users/users/config.py
users/users/s3.py

Relates to https://github.com/epam/badgerdoc/issues/639

fix: fix https flag hadling

---

web/src/components/basement/basement-popup/basement-popup.module.scss
web/src/shared/no-data/no-data.module.scss

Closes [#712](https://github.com/epam/badgerdoc/issues/712)

refactor: popup dialog does not display correctly

---

web/src/connectors/documents-table-connector/documents-table-connector.tsx

Closes [#721](https://github.com/epam/badgerdoc/issues/721)

fix: deleted element is still selected after the moment when its removed

---

web/src/connectors/documents-page-control-connector/documents-page-control-connector.module.scss
web/src/connectors/documents-page-control-connector/documents-page-control-connector.tsx
web/src/connectors/documents-table-connector/documents-table-connector.module.scss
web/src/shared/components/table-wrapper/table-wrapper.module.scss

Closes [#722 ](https://github.com/epam/badgerdoc/issues/722)

fix: buttons are overlapped when they are focused

---

web/package.json
web/src/components/task/task-sidebar-flow/__tests__/annotation-list.test.tsx
web/src/components/task/task-sidebar-flow/annotation-list.tsx
web/src/connectors/task-annotator-connector/task-annotator-context.tsx
web/src/setupTests.tsx
web/yarn.lock

In the scope of this PR, tests for "AnnotationList" component were fixed.

test: update tests for "AnnotationList" component

---

README.md

Based on https://github.com/epam/badgerdoc/pull/705#issuecomment-1666435313

feat: use dynamic list of contributors

---

web/src/components/task/task-sidebar/finish-button/finish-button.tsx

removed useCallback from finish validation

fix: removed useCallback from finish validation

---

web/src/components/job/validation-type-picker/validation-type-picker.tsx

Added 'Validation only' description in validation picker

fix: added 'Validation only' desc in validation picker

---

web/src/components/task/task-sidebar/finish-button/finish-button.tsx
web/src/connectors/edit-job-connector/edit-job-connector.tsx

'Confirm' modal returns when validation finished.

fix: 'confirm' modal returns when validation finished.

---

README.md
airflow/.env.example

PR adds documentation how to setup service account for communication between Airflow and Badgerdoc

docs: setup airflow with service-account

---

annotation/annotation/annotations/resources.py
annotation/annotation/categories/services.py
annotation/annotation/jobs/services.py
annotation/annotation/microservice_communication/jobs_communication.py
annotation/tests/conftest.py
annotation/tests/test_microservices_search.py
docker-compose-dev.yaml
jobs/jobs/categories.py
jobs/jobs/db_service.py
jobs/jobs/main.py
jobs/jobs/run_job_funcs.py
jobs/jobs/schemas.py
jobs/tests/conftest.py
jobs/tests/fixtures_models.py
jobs/tests/fixtures_schemas.py
jobs/tests/test_categories.py
web/src/api/hooks/pipelines.ts
web/src/connectors/edit-job-connector/edit-job-connector.tsx

Closes: https://github.com/epam/badgerdoc/issues/841

feat: add categories to job on annotation commit

---

annotation/annotation/annotations/__init__.py
annotation/annotation/annotations/main.py
annotation/annotation/annotations/resources.py
annotation/annotation/categories/resources.py
annotation/annotation/distribution/resources.py
annotation/annotation/filters.py
annotation/annotation/jobs/resources.py
annotation/annotation/jobs/services.py
annotation/annotation/metadata/resources.py
annotation/annotation/microservice_communication/task.py
annotation/annotation/revisions/resources.py
annotation/annotation/tasks/resources.py
annotation/annotation/tasks/services.py
annotation/tests/conftest.py
annotation/tests/test_annotators_overall_load.py
annotation/tests/test_get_child_categories.py
annotation/tests/test_get_pages_info.py
annotation/tests/test_job_categories.py
annotation/tests/test_microservices_search.py
annotation/tests/test_post.py
annotation/tests/test_post_annotation.py
annotation/tests/test_post_next_task.py
annotation/tests/test_post_unassgined_files.py
annotation/tests/test_search_kafka.py
annotation/tests/test_tasks_crud_cr.py
annotation/tests/test_update_job.py
annotation/tests/test_validation.py
jobs/tests/conftest.py

Bug discovered while testing: https://github.com/epam/badgerdoc/issues/841

fix: add idempotence to create annotation endpoint 

---

annotation/.pre-commit-config.yaml
annotation/tests/test_annotations.py
annotation/tests/test_post_annotation.py

Created a pytest unit test for annotation/annotation/annotations/main.py/row_to_dict()

test(annotation): cover row to dict function

---

annotation/tests/test_jobs.py

covered all functions except filter_job_categories and create_job

test(annotation): cover jobs.services.py functions

---

docker-compose-dev.yaml
ml_server/Dockerfile

- Add missing main.py to ml-sever image
- Change the name of ml-server container in compose file

fix: ml-server build

---

jobs/jobs/db_service.py
jobs/jobs/main.py
jobs/jobs/utils.py

add validations for:
- check if the given referred files exist in database
- check if the job name is already in use
closes: #997

fix: create_job has no check for dublicate job name and files exist or not 

---

web/src/components/categories/categories-selection-mode-toggle/categories-selection-mode-toggle.scss
web/src/components/categories/categories-selection-mode-toggle/categories-selection-mode-toggle.tsx

feat: Rename box annotation type to text-box

---

web/src/connectors/documents-page-control-connector/documents-page-control-connector.tsx
web/src/connectors/documents-table-connector/documents-table-connector.tsx
web/src/icons/sort-icon/sort-icon.tsx
web/src/shared/contexts/documents-search.tsx

Add "Sort ascending/descending" functionality to "Sort by" drop-down for files on the "Documents" tab

feat: Add "Sort ascending/descending" functionality for files sorting  #802

---

web/src/App.tsx
web/src/connectors/documents-table-connector/documents-table-connector.tsx
web/src/pages/jobs/edit-job-page.tsx

closes: [https://github.com/epam/badgerdoc/issues/784](https://github.com/epam/badgerdoc/issues/784)

feat: User is able to proceed to the next step w/o selecting a file #784

---

web/src/components/dataset/dataset-choose-form.tsx

On 'Choose' modal saves changes and closes
Closes https://github.com/epam/badgerdoc/issues/655

fix: Add to dataset modal not closing on Choose #655
